name: Deploy .NET API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop Running API
        shell: powershell
        run: |
          taskkill /IM dotnet.exe /F

      - name: Restore Packages
        run: dotnet restore
        shell: powershell

      - name: Build Project
        run: dotnet build --configuration Release --no-restore
        shell: powershell

      - name: Publish API
        run: dotnet publish --configuration Release --output C:\deploy\dotnet_api --no-build
        shell: powershell

      - name: Start API
        shell: powershell
        run: |
          Start-Process "dotnet" "C:\deploy\dotnet_api\MonitoringStack.dll"