name: Deploy .NET API to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "MonitoringStackAPI"

      - name: Restore
        run: dotnet restore
        shell: powershell

      - name: Build
        run: dotnet build -c Release --no-restore
        shell: powershell

      - name: Publish
        run: dotnet publish -c Release -o C:\inetpub\monitoring_api --no-build
        shell: powershell

      - name: Start IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "MonitoringStackAPI"