name: Deploy .NET API to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore packages
        run: dotnet restore
        shell: powershell

      - name: Build project
        run: dotnet build -c Release --no-restore
        shell: powershell

      - name: Publish project
        run: dotnet publish -c Release -o C:\inetpub\monitoring_api --no-build
        shell: powershell

      - name: Restart IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "MonitoringStackAPI"